{
 "title": "Crypto Arbitrage Bot Monitoring",
 "description": "Monitoring of arbitrage trading bot performance and metrics",
 "tags": [
  "crypto",
  "arbitrage",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Top 10 Book Ticker Events (Operations per Second)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (symbol) (rate(book_ticker_events_total[5m])))"
    }
   ]
  },
  {
   "title": "Book Ticker Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(book_ticker_events_total[1m]))",
     "legendFormat": "Total Events Rate"
    }
   ]
  },
  {
   "title": "Top 15 Processed Arbitrage Chains (Operations per Second)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(15, sum by (symbol_a, symbol_b, symbol_c) (rate(processed_chains_total[5m])))"
    }
   ]
  },
  {
   "title": "Processed Chains Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(processed_chains_total[1m]))",
     "legendFormat": "Chains Processing Rate"
    }
   ]
  },
  {
   "title": "Success Rate (%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(profit_orders_total[5m])) / sum(rate(processed_chains_total[5m]))) * 100",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Profit Orders Found",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(profit_orders_total[5m]))",
     "legendFormat": "Profit Orders Rate"
    }
   ]
  },
  {
   "title": "Last 30 Orders Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "profit_orders_total{status=~\"new|filled|canceled\"}"
    }
   ]
  }
 ]
}