services:
  bot:
    build:
      context: .
      args:
        - SERVICE_NAME=bot
        - BUILD_PROFILE=release-lto
    container_name: bot
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9007:9007"
    network_mode: host
    environment:
      - RUST_LOG=info
    volumes:
      - ./config.toml:/config.toml:ro
    healthcheck:
      test: [ "CMD", "nc", "-zv", "127.0.0.1", "9000" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./resources/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    network_mode: host
    depends_on:
      bot:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_BASIC_ENABLED=true
      - GF_AUTH_LDAP_ENABLED=false
    volumes:
      - ./resources/grafana/dashboards/:/var/lib/grafana/dashboards/
      - ./resources/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/bot.yml
      - ./resources/grafana/datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    network_mode: host


volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
