version: 3

vars:
  RUST_IMAGE: "rustlang/rust:nightly"
  TARP_IMAGE: "xd009642/tarpaulin:develop-nightly"
  DOCKER_RUN: >-
    docker run --rm -t --init
    -u $(id -u):$(id -g)
    -e TERM=xterm-256color
    -e CARGO_HOME=/cargo
    -e RUSTUP_HOME=/rustup
    -v $HOME/.cargo:/cargo:z
    -v $HOME/.rustup:/rustup:z
    -v {{.PWD}}:/src:z
    -w /src
    {{.RUST_IMAGE}}

tasks:
  run:
    run: once
    cmds:
      - task: check
      - task: check-docs
      - task: test-docs
      - task: test-versions
      - task: dependencies-are-sorted
      - task: test
      - task: coverage

  check:
    run: once
    cmds:
      - >-
        {{.DOCKER_RUN}} sh -c "
        export RUSTUP_TOOLCHAIN=nightly;
        rustup component add clippy rustfmt >/dev/null 2>&1;
        exec cargo clippy --workspace --all-targets --all-features -- -D warnings"
      - >-
        {{.DOCKER_RUN}} sh -c "exec cargo +nightly fmt --all --check"

  check-docs:
    run: once
    cmds:
      - >-
        {{.DOCKER_RUN}} sh -c "
        export RUSTUP_TOOLCHAIN=nightly;
        exec cargo doc --workspace --all-features --no-deps"

  test-versions:
    run: once
    cmds:
      - >-
        {{.DOCKER_RUN}} sh -c "
        export RUSTUP_TOOLCHAIN=nightly;
        exec cargo test --workspace --all-features --all-targets"

  test-docs:
    run: once
    cmds:
      - >-
        {{.DOCKER_RUN}} sh -c "
        export RUSTUP_TOOLCHAIN=nightly;
        exec cargo test --all-features --doc"

  dependencies-are-sorted:
    run: once
    cmds:
      - >-
        {{.DOCKER_RUN}} sh -c "
        export RUSTUP_TOOLCHAIN=nightly;
        command -v cargo-sort >/dev/null 2>&1 || cargo install cargo-sort;
        exec cargo sort --workspace --grouped --check"

  test:
    run: once
    cmds:
      - >-
        {{.DOCKER_RUN}} sh -c "
        export RUSTUP_TOOLCHAIN=nightly;
        exec cargo test --workspace --all"

  coverage:
    run: once
    cmds:
      - >-
        docker run --rm -t --init
        -u $(id -u):$(id -g)
        -e TERM=xterm-256color
        -e RUSTUP_TOOLCHAIN=nightly
        -v {{.PWD}}:/src
        -v {{.PWD}}/target:/src/target
        -w /src
        --security-opt seccomp=unconfined
        {{.TARP_IMAGE}}
        sh -c "exec cargo +nightly tarpaulin --all-features --workspace --timeout 120 --out Html --output-dir target/coverage"
