global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bot'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9007']
        labels:
          instance: 'bot-docker'
          app: 'crypto-arbitrage'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']