/// Errors that may be returned by the TokenSwap program.

#[derive(Debug, thiserror::Error, PartialEq)]
pub enum ErrorCode {
    #[error("Not approved")]
    NotApproved,
    /// The owner of the input isn't set to the program address generated by the
    /// program.
    #[error("Input account owner is not the program address")]
    InvalidOwner,
    /// The input token account is empty.
    #[error("Input token account empty")]
    EmptySupply,
    /// The input token is invalid for swap.
    #[error("InvalidInput")]
    InvalidInput,
    /// Address of the provided pool token mint is incorrect
    #[error("Address of the provided lp token mint is incorrect")]
    IncorrectLpMint,
    /// Exceeds desired slippage limit
    #[error("Exceeds desired slippage limit")]
    ExceededSlippage,
    /// Given pool token amount results in zero trading tokens
    #[error("Given pool token amount results in zero trading tokens")]
    ZeroTradingTokens,
    #[error("Not support token_2022 mint extension")]
    NotSupportMint,
    #[error("invaild vault")]
    InvalidVault,
    #[error("Init lp amount is too less(Because 100 amount lp will be locked)")]
    InitLpAmountTooLess,
    #[error("TransferFee calculate not match")]
    TransferFeeCalculateNotMatch,
    #[error("Math overflow")]
    MathOverflow,
    #[error("Insufficient vault")]
    InsufficientVault,
    #[error("Invalid fee model")]
    InvalidFeeModel,
    #[error("Fee is zero")]
    NoFeeCollect,
}
